//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KZDev.PrimeTime.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KZDev.PrimeTime.Resources.ProductionStrings", typeof(ProductionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule-zone projection requires IPrimeClock so the local schedule time zone can be resolved. Use a clock implementation such as PrimeClock or PrimeTestClock; IPrimeTime-only contexts are not supported..
        /// </summary>
        internal static string Argument_ScheduleZoneRequiresIPrimeClock {
            get {
                return ResourceManager.GetString("Argument_ScheduleZoneRequiresIPrimeClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must use DateTimeKind.Utc so it represents an unambiguous absolute instant on the UTC timeline..
        /// </summary>
        internal static string Argument_UtcDateTimeMustBeUtcKind {
            get {
                return ResourceManager.GetString("Argument_UtcDateTimeMustBeUtcKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an invalid local time window on the calendar date for {0}..
        /// </summary>
        internal static string InvalidOperation_ExpectedInvalidLocalTimeWindow {
            get {
                return ResourceManager.GetString("InvalidOperation_ExpectedInvalidLocalTimeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a valid local day-time fire instant within {0} calendar days for time zone &apos;{1}&apos; and target time of day &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidOperation_LocalDayTimeFireInstantNotFound {
            get {
                return ResourceManager.GetString("InvalidOperation_LocalDayTimeFireInstantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve RunAfter instant after a spring-forward gap..
        /// </summary>
        internal static string InvalidOperation_RunAfterSpringForwardGapUnresolved {
            get {
                return ResourceManager.GetString("InvalidOperation_RunAfterSpringForwardGapUnresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve RunBefore instant before a spring-forward gap..
        /// </summary>
        internal static string InvalidOperation_RunBeforeSpringForwardGapUnresolved {
            get {
                return ResourceManager.GetString("InvalidOperation_RunBeforeSpringForwardGapUnresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change a non-repeating timer to a repeating timer..
        /// </summary>
        internal static string InvalidOperation_TimerNonRepeatingToRepeating {
            get {
                return ResourceManager.GetString("InvalidOperation_TimerNonRepeatingToRepeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected ZoneLocalMapping.Count: {0}..
        /// </summary>
        internal static string InvalidOperation_UnexpectedZoneLocalMappingCount {
            get {
                return ResourceManager.GetString("InvalidOperation_UnexpectedZoneLocalMappingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported callback kind: {0}.
        /// </summary>
        internal static string InvalidOperation_UnsupportedTimerCallbackKind {
            get {
                return ResourceManager.GetString("InvalidOperation_UnsupportedTimerCallbackKind", resourceCulture);
            }
        }
    }
}
