//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KZDev.PrimeTime.Testing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestingStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestingStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KZDev.PrimeTime.Testing.Resources.TestingStrings", typeof(TestingStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual time per real second must be between 100 milliseconds and 1 hour, inclusive..
        /// </summary>
        internal static string ArgumentOutOfRange_StartRunRateOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_StartRunRateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A previous Stop() returned false because the automatic runner did not join within {0} seconds, and the runner thread may still be executing. Start(), SetTime, Advance, and RunFor are blocked until that thread exits or this PrimeTestClock instance is discarded. This typically indicates the runner loop is blocked inside a ClockEvents subscriber or virtual-time dispatch callback..
        /// </summary>
        internal static string InvalidOperation_RunnerStopJoinFailed {
            get {
                return ResourceManager.GetString("InvalidOperation_RunnerStopJoinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out stopping the automatic runner after {0} seconds..
        /// </summary>
        internal static string InvalidOperation_RunnerStopJoinTimedOut {
            get {
                return ResourceManager.GetString("InvalidOperation_RunnerStopJoinTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start waited for an overlapping Stop to finish joining the automatic runner, but Stop did not complete within {0} seconds ({1} second join timeout plus scheduling slack). This typically indicates the runner loop is blocked inside a ClockEvents subscriber or virtual-time dispatch callback..
        /// </summary>
        internal static string InvalidOperation_StartWaitForOverlappingStopTimedOut {
            get {
                return ResourceManager.GetString("InvalidOperation_StartWaitForOverlappingStopTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change a non-repeating timer to a repeating timer..
        /// </summary>
        internal static string InvalidOperation_TimerNonRepeatingToRepeating {
            get {
                return ResourceManager.GetString("InvalidOperation_TimerNonRepeatingToRepeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported callback kind: {0}.
        /// </summary>
        internal static string InvalidOperation_UnsupportedTimerCallbackKind {
            get {
                return ResourceManager.GetString("InvalidOperation_UnsupportedTimerCallbackKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move the test clock&apos;s virtual time backward while an interval timer registration is active..
        /// </summary>
        internal static string InvalidOperation_VirtualTimeBackwardWhileIntervalTimerActive {
            get {
                return ResourceManager.GetString("InvalidOperation_VirtualTimeBackwardWhileIntervalTimerActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move the test clock&apos;s virtual time backward while it is running..
        /// </summary>
        internal static string InvalidOperation_VirtualTimeBackwardWhileRunning {
            get {
                return ResourceManager.GetString("InvalidOperation_VirtualTimeBackwardWhileRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual time cannot be changed while Stop() is joining the automatic runner. Wait for Stop() to complete before calling SetTime, Advance, or RunFor..
        /// </summary>
        internal static string InvalidOperation_VirtualTimeMutationDuringStopJoin {
            get {
                return ResourceManager.GetString("InvalidOperation_VirtualTimeMutationDuringStopJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaled virtual elapsed time exceeds the representable TimeSpan range..
        /// </summary>
        internal static string Overflow_ScaledVirtualElapsedExceedsTimeSpanRange {
            get {
                return ResourceManager.GetString("Overflow_ScaledVirtualElapsedExceedsTimeSpanRange", resourceCulture);
            }
        }
    }
}
