<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <UseAppHost>true</UseAppHost>
        <GenerateProgramFile>false</GenerateProgramFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Src\KZDev.PrimeTime\KZDev.PrimeTime.csproj" />
        <ProjectReference Include="..\..\Src\KZDev.PrimeTime.Testing\KZDev.PrimeTime.Testing.csproj" />
        <ProjectReference Include="..\..\Src\KZDev.SystemClock.PrimeTime\KZDev.SystemClock.PrimeTime.csproj" />
        <ProjectReference Include="..\..\Src\KZDev.SystemClock.PrimeTime.Testing\KZDev.SystemClock.PrimeTime.Testing.csproj" />
        <ProjectReference Include="..\KZDev.PrimeTime.Tst.UnitTestBase\KZDev.PrimeTime.Tst.UnitTestBase.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="KZDev.PrimeTime" />
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
        <Compile Remove="UsingIPrimeClockDayTimeTimers.cs" />
        <Compile Remove="UsingDayTimeNodaLocalWallTimeScheduling.cs" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
        <PackageReference Include="Microsoft.Bcl.TimeProvider" />
    </ItemGroup>

</Project>
