<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>KZDev.SystemClock.PrimeTime</RootNamespace>
		<AssemblyName>KZDev.SystemClock.PrimeTime.Testing</AssemblyName>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<Description>Virtual-time test clock and contracts for KZDev.SystemClock.PrimeTime (BCL subset).</Description>
		<DefineConstants>$(DefineConstants);SYSTEMCLOCK</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Label="Package">
		<Title>KZDev SystemClock PrimeTime Testing</Title>
		<PackageId>KZDev.SystemClock.PrimeTime.Testing</PackageId>
		<PackageReleaseNotesSourceFile>..\..\Docs\Notes\KZDev.SystemClock.PrimeTime.Testing.release-notes.md</PackageReleaseNotesSourceFile>
		<PackageTags>KZDev,Utilities,Time,Timer,Testing</PackageTags>
		<PackageReadmeFile>docs\README.md</PackageReadmeFile>
		<PackageIcon>images\icon.png</PackageIcon>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageDescription>$(Description)</PackageDescription>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<RepositoryUrl>https://github.com/kzdev-net/kzdev.primetime</RepositoryUrl>
	</PropertyGroup>
	<PropertyGroup Condition="'$(IsPacking)' == 'true'">
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<IsPackable>true</IsPackable>
	</PropertyGroup>
	<PropertyGroup Condition="'$(IsPacking)' != 'true'">
		<DefineConstants>$(DefineConstants);NOT_PACKAGING</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
		<PackageReference Include="Microsoft.Bcl.TimeProvider" />
		<PackageReference Include="System.Threading.Tasks.Extensions" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\KZDev.SystemClock.PrimeTime\KZDev.SystemClock.PrimeTime.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\Package\KZDev.SystemClock.PrimeTime.Testing.readme.md" Pack="true" Visible="false" PackagePath="docs\README.md" />
		<None Include="..\Package\nuget.icon.png" Pack="true" Visible="false" PackagePath="images\icon.png" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="KZDev.PrimeTime.UnitTests" />
		<InternalsVisibleTo Include="KZDev.SystemClock.PrimeTime.UnitTests" />
	</ItemGroup>
	<Import Project="..\Shared\KZDev.PrimeTime.Common.Testing.Shared\KZDev.PrimeTime.Common.Testing.Shared.projitems" Label="Testing" />

</Project>
