<Project>
    <!--
    Import the next higher level Directory.Build.props file.
    -->
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />
    <!--
    Dev folder: development-production/example projects.
    -->
    <PropertyGroup Label="DevProdGlobals">
    </PropertyGroup>
</Project>
