<Project>
    <!--
    Perf folder: benchmark projects. Profile configuration, net9|net8, IsPackable false.
    Define folder-level properties first, then import Source-level.
    -->
    <PropertyGroup Label="PerfGlobals">
        <Configurations>Debug;Release;Profile</Configurations>
        <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />
</Project>
