<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>KZDev.PrimeTime.ReleaseAggregation.Cli</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\KZDev.PrimeTime.ReleaseAggregation\KZDev.PrimeTime.ReleaseAggregation.csproj" />
    </ItemGroup>

</Project>
