<Project>
    <!-- 
    Define Solution-Level properties
   -->
    <PropertyGroup Label="SourceGlobals">
        <Configurations>Debug;Release</Configurations>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <UseArtifactsOutput>true</UseArtifactsOutput>
        <ArtifactsPath>$(MSBuildThisFileDirectory)..\artifacts</ArtifactsPath>
        <RootNamespace>KZDev.PrimeTime</RootNamespace>
    </PropertyGroup>
</Project>
